apiVersion: v1
kind: Service
metadata:
  name: cloud-infra-demo-api
  namespace: cloud-infra-demo
spec:
  type: LoadBalancer
  selector:
    app: cloud-infra-demo-api
  ports:
    - port: 80
      targetPort: 3000
